<VentanaInicial@GridLayout>:
    cols: 3
    rows: None

    row_default_height: 50
    row_force_default: True

    #col_default_width: 50
    #col_force_default: True


    Button:
        text: "A"
        size_hint: .1, .1
    Button:
        text: "B"
    Button:
        text: "C"
    Button:
        text: "D"
        size_hint: .1, .1
    Button:
        text: "E"
    Button:
        text: "F"
    Button:
        text: "G"
        size_hint: .1, .1


VentanaInicial: