<VentanaInicial>
    Button:
        size_hint_y: None
        height: 50
        markup: True
        id: boton1
        text: "BOTON1"
        on_press: root.click()
        on_release: root.fin_click()

    Button:
        size_hint_y: None
        height: 50
        markup: True
        text: "BOTON2"
        id: boton2
        on_press: root.click()
        on_release: root.fin_click()

VentanaInicial: