#:import C kivy.utils.get_color_from_hex

<VentanaInicial@FloatLayout>:

    Button:
        text: "A"
        size_hint: .3, .3
        pos_hint: {"center_x": .5, "center_y": .5}
        on_press: root.contenido()
        background_color: C("#FFFFFF")
        background_normal: ""
        text: "BOTON DE MUESTRA"
        color: 255, 255, 255, 1
        bold: True
        font_size: '20sp'
        id: boton1

VentanaInicial: